Comanda.Site/Controllers/ComandaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Comanda.Business;
using Comanda.Model.Classes;
using Comanda.Excecao;
using Comanda.Site.ViewModels;

namespace Comanda.Site.Controllers
{
    public class ComandaController : Controller
    {
        //
        // GET: /Comanda/
                
        public ActionResult Pedidos()
        {
            var viewmodel = new Site.ViewModels.PedidosViewModel();

            try
            {
                using (var business = new Business.Business())
                {
                    viewmodel.ListaSituacao = DataAccess.Tabelas.Situacao.ListaTotal;
                }
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw; 
            }           

            return View(viewmodel);
        }
        public ActionResult Clientes()
        {
            return View();
        }
        public ActionResult Produtos()
        {
            return View();
        }
        public ActionResult ListaPedidos()
        {
            var situacao = DataAccess.Tabelas.Situacao.ListaTotal.ToList();
            return View(situacao);
        }
        public ActionResult Teste()
        {            
            return View();
        }
        [HttpPost]
        public PartialViewResult CadastraPedidos(ViewModels.PedidosViewModel form)
        {
            
            try 
            {
                var model = new PedidosModel() { 
                 DataHora = DateTime.Now,
                 Qtd = form.Qtd,
                 Preco = form.Preco,
                 ClienteId = form.ClienteId,
                 ProdutoId = form.ProdutoId,
                 SituacaoId = form.SituacaoId
                };

                DataAccess.Tabelas.Pedidos.Add(model);                
                
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }
            
            return PartialView("~/Views/PartialViews/Sucesso.cshtml");
        }
        [HttpPost]
        public PartialViewResult ClienteCadastro(ViewModels.PedidosViewModel form)
        {
            return PartialView("~/Views/PartialViews/CadastraCliente.cshtml", form);
        }
        [HttpPost]
        public PartialViewResult ProdutoCadastro(ViewModels.PedidosViewModel form)
        {
            return PartialView("~/Views/PartialViews/CadastraProduto.cshtml", form);
        }
        [HttpPost]
        public JsonResult SalvaCliente(ViewModels.PedidosViewModel form)
        {
            var retorno = Json("{}", JsonRequestBehavior.AllowGet);
            try
            {

                var cliente = new ClienteModel() { Nome = form.Nome.Trim(), Comentario = form.Comentario.Trim() };

                using (var business = new Business.Business())
                {
                    if (business.ClienteExiste(cliente))
                    {
                        cliente = DataAccess.Tabelas.Clientes.ListaTotal.Find(x => x.Nome.Trim() == cliente.Nome && x.Comentario.Trim() == cliente.Comentario);
                    }
                    else
                    {
                        DataAccess.Tabelas.Clientes.Add(cliente);
                        cliente = DataAccess.Tabelas.Clientes.ListaTotal.Last();
                    }
                }

                retorno = Json(new { cliente.ClienteId, cliente.Nome, cliente.Comentario }, JsonRequestBehavior.AllowGet);                
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }

            return retorno;
        }
        [HttpPost]
        public JsonResult SalvaProduto(ViewModels.PedidosViewModel form)
        {
            var retorno = Json("{}", JsonRequestBehavior.AllowGet);

            try
            {
                var produto = new ProdutoModel() { Descricao = form.Produto.Trim(), Preco = form.Preco };

                using (var business = new Business.Business())
                {
                    if (business.ProdutoExiste(produto))
                    {
                        produto = DataAccess.Tabelas.Produtos.ListaTotal.Find(x => x.Descricao.Trim() == produto.Descricao && x.Preco == produto.Preco);
                    }
                    else
                    {
                        DataAccess.Tabelas.Produtos.Add(produto);
                        produto = DataAccess.Tabelas.Produtos.ListaTotal.Last();
                    }
                }

                retorno = Json(new { produto.ProdutoId, produto.Descricao, produto.Preco }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }

            return retorno;
        }
        [HttpPost]
        public JsonResult ListaClientes() 
        {
            var retorno = Json("{}", JsonRequestBehavior.AllowGet);

            try
            {
                var lista = DataAccess.Tabelas.Clientes.ListaTotal
                           .Select(x => x.ClienteId.ToString("00") + " - " + 
                                        x.Nome + (x.Comentario.Trim().Length > 0 ? " - " + 
                                        x.Comentario : ""))
                                        .ToList<string>();
                retorno = Json(lista, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }
            
            return retorno; 
        }
        [HttpPost]
        public JsonResult ListaProdutos()
        {
            var retorno = Json("{}", JsonRequestBehavior.AllowGet);

            try
            {
                var lista = DataAccess.Tabelas.Produtos.ListaTotal.Select(x => x.ProdutoId.ToString("00") + " - "  + x.Descricao + " - " + x.Preco.ToString("0.00")).ToList<string>();
                retorno = Json(lista, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }

            return retorno; 
        }        
        [HttpPost]
        public JsonResult DeletaPedido(string datahora)
        {
            var retorno = Json("{}", JsonRequestBehavior.AllowGet);

            try
            {                
                var entity = DataAccess.Tabelas.Pedidos.ListaTotal.FirstOrDefault(x => x.DataHora.ToString("dd/MM/yyyy HH:mm:ss") == datahora);
                entity.SituacaoId = DataAccess.Tabelas.Situacao.ListaTotal.Max(x => x.SituacaoId);
                DataAccess.Tabelas.Pedidos.Update(entity);
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }
            return retorno;
        }
        [HttpPost]
        public JsonResult CarregaClientes()
        {
            var retorno = Json("{}", JsonRequestBehavior.AllowGet);
            try
            {
                var lista = DataAccess.Tabelas.Clientes.ListaTotal;
                retorno = Json(lista.Select(x => new {ClienteId = x.ClienteId.ToString("00"),x.Nome,x.Comentario,Editar = x.ClienteId }), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }
            return retorno;
        }
        [HttpPost]
        public JsonResult CarregaProdutos()
        {
            var retorno = Json("{}", JsonRequestBehavior.AllowGet);
            try
            {
                var lista = DataAccess.Tabelas.Produtos.ListaTotal;
                retorno = Json(lista.Select(x => new { ProdutoId = x.ProdutoId,Descricao = x.Descricao,Preco = x.Preco.ToString("0.00"),Editar = x.ProdutoId }), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }
            return retorno;
        }
        [HttpPost]
        public PartialViewResult EditarCliente(string Id)
        {
            var retorno = new PartialViewResult();
            try
            {
                var dado = DataAccess.Tabelas.Clientes.ListaTotal.FirstOrDefault(x => x.ClienteId == int.Parse(Id));
                retorno = PartialView("~/Views/PartialViews/EditarCliente.cshtml", dado);
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }
            return retorno;
        }
        [HttpPost]
        public PartialViewResult EditarProduto(string Id)
        {
            var retorno = new PartialViewResult();
            try
            {
                var dado = DataAccess.Tabelas.Produtos.ListaTotal.FirstOrDefault(x => x.ProdutoId == int.Parse(Id));
                retorno = PartialView("~/Views/PartialViews/EditarProduto.cshtml", dado);
            }
            catch (Exception ex)
            {
                new Excecao.Excecao().GravaExcecao(ex, "{}");
                throw;
            }
            return retorno;
        }
        [HttpPost]
        public JsonResult AtualizaDadosCliente(ClienteModel model)
        {
            var retorno = Json("{}", JsonRequestBehavior.AllowGet);

            try
            {
                DataAccess.Tabelas.Clientes.Update(model);
                retorno = Json(model, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

Comanda.Site/Views/PartialViews/CadastraCliente.cshtml
@model Comanda.Site.ViewModels.PedidosViewModel

<style type="text/css">

.modal-body .form-horizontal .col-sm-2,
.modal-body .form-horizontal .col-sm-10 {
    width: 100%
}

.modal-body .form-horizontal .control-label {
    text-align: left;
}
.modal-body .form-horizontal .col-sm-offset-2 {
    margin-left: 15px;
}

</style>

<!-- Modal -->
<div class="modal fade" id="ModalClienteCadastro" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                   Cliente não cadastrado, deseja cadastra-lo?
                </h4>
            </div>
            <!-- Modal Body -->            
            <div class="container">
                <div class="row">
                    <label class="form-control-static control-label col-md-4" for="ModalClienteNome">Nome/Apelido:</label>
                    <p class="form-control-static col-md-8" id="ModalClienteNome">@Model.Nome</p>
                </div>
                <div class="row">
                    <label class="form-control-static control-label col-md-4" for="ModalClienteComentario">Comentário:</label>
                    <p class="form-control-static col-md-8" id="ModalClienteComentario">@Model.Comentario</p>
                </div>
            </div>
            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"> Não </button>
                <button type="button" class="btn btn-primary" id="ModalClienteSalvar"> Sim </button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">   

    $("#ModalClienteSalvar").on("click", function () {
        var form = {
            "Nome": $("#ModalClienteNome").text(),
            "Comentario": $("#ModalClienteComentario").text()
        };
                
        MontaAjax('@Url.Action("SalvaCliente", "Comanda")', form, function (data) {            
            $("#hdnClienteId").val(data.ClienteId);
            $("#txtNome").val(data.Nome);
            $("#txtComentario").val(data.Comentario);

            $("#ModalClienteCadastro").modal("hide");
            $("#collapseProduto").collapse("show");
        });
        
    });
</script>

Comanda.Site/Views/PartialViews/CadastraProduto.cshtml
@model Comanda.Site.ViewModels.PedidosViewModel

<style type="text/css">
    .modal-body .form-horizontal .col-sm-2,
    .modal-body .form-horizontal .col-sm-10 {
        width: 100%;
    }

    .modal-body .form-horizontal .control-label {
        text-align: left;
    }

    .modal-body .form-horizontal .col-sm-offset-2 {
        margin-left: 15px;
    }
</style>

<!-- Modal -->
<div class="modal fade" id="ModalProduto" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Produto não cadastrado, deseja cadastra-lo?
                </h4>
            </div>

            <!-- Modal Body -->            
            <div class="container">
                <div class="row">
                    <label class="form-control-static control-label col-md-4" for="ModalProdutoDesc">Produto:</label>
                    <p class="form-control-static col-md-8" id="ModalProdutoDesc">@Model.Produto</p>
                </div>
                <div class="row">
                    <label class="form-control-static control-label col-md-4" for="ModalProdutoPreco">Preço:</label>
                    <p class="form-control-static col-md-8" id="ModalProdutoPreco">@Model.Preco.ToString("0.00")</p>
                </div>
            </div>
            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"> Não </button>
                <button type="button" class="btn btn-primary" id="ModalProdutoSalvar"> Sim </button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">


    $("#ModalProdutoSalvar").on("click", function () {
        var form = {
            "Produto": $("#ModalProdutoDesc").text(),
            "Preco": $("#ModalProdutoPreco").text()
        };
        
        MontaAjax('@Url.Action("SalvaProduto", "Comanda")', form, function (data) {
            
            $("#hdnProdutoId").val(data.ProdutoId);
            $("#txtProduto").val(data.Descricao);
            $("#txtPreco").val(data.Preco);
                        
            $("#ModalProduto").modal("hide");
        });

    });
</script>

Comanda.Site/Views/PartialViews/EditarCliente.cshtml
@model Comanda.Model.Classes.ClienteModel

<style type="text/css">
    #EditaCliente
    {
        margin-left:10px;
        margin-right:10px;
    }
    #ModalEditarCliente > div > div > div.modal-header > h4
    {
        margin-left:10px
    }
</style>

<!-- Modal -->
<div class="modal fade" id="ModalEditarCliente" tabindex="-1" role="dialog"   aria-hidden="true">    
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Editar Cliente</h4>
            </div>
            <div class="modal-body">
                <div id="EditaCliente" class="form-group row">
                    <input type="hidden" id="hdnClienteId" value="@Model.ClienteId">
                    <label for="txtNome">Nome/Apelido:</label>
                    <input type="text" class="form-control margin-bottom" id="txtNome" autocomplete="off" placeholder="Ex: Eduardo,Pedrinho,Confirma,etc." value="@Model.Nome">                    

                    <label for="txtComentario" class="margin-top">Comentário:</label>
                    <input type="text" class="form-control" id="txtComentario" placeholder="Ex: Meu vizinho, mora na esquina, primo de fulano,etc." value="@Model.Comentario">
                    
                </div>
            </div>
            <div class="modal-footer">
                <button id="EnviarEditarCliente" type="button" class="btn btn-primary" data-dismiss="modal">Enviar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        
        MascaraMaiuscula($("#EditaCliente > #txtNome"));
        MascaraMaiuscula($("#EditaCliente > #txtComentario"));

        $("#EnviarEditarCliente").on("click", function () {
            var model = {
                "ClienteId": $("#EditaCliente > #hdnClienteId").val(),
                "Nome": $("#EditaCliente > #txtNome").val(),
                "Comentario": $("#EditaCliente > #txtComentario").val()
            };

            MontaAjax('@Url.Action("AtualizaDadosCliente", "Comanda")', model, function (data) {
                GridClientesLoad();
            });

        });
    });
</script>

Comanda.Site/Views/PartialViews/EditarProduto.cshtml
@model Comanda.Model.Classes.ProdutoModel

<style type="text/css">
    #EditaProduto {
        margin-left: 10px;
        margin-right: 10px;
    }

    #ModalEditarProduto > div > div > div.modal-header > h4 {
        margin-left: 10px;
    }
</style>

<!-- Modal -->
<div class="modal fade" id="ModalEditarProduto" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Editar Produto</h4>
            </div>
            <div class="modal-body">
                <div id="EditaProduto" class="form-group row">
                    <input type="hidden" id="hdnProdutoId" value="@Model.ProdutoId">
                    <label for="txtProduto" class="margin-top">Produto:</label>
                    <input type="text" class="form-control margin-bottom" id="txtProduto" autocomplete="off" placeholder="Ex: Skol,Brahma,chicletinho,etc." value="@Model.Descricao">
                    
                    <label for="txtPreco" class="margin-top">Preço:</label>
                    <input type="text" class="form-control" style="width:20%;" id="txtPreco" value="@Model.Preco.ToString("0.00")">
                    
                </div>
            </div>
            <div class="modal-footer">
                <button id="EnviarEditarProduto" type="button" class="btn btn-primary" data-dismiss="modal">Enviar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {

        MascaraMaiuscula($("#EditaProduto > #txtProduto"));
        MascaraPreco($("#EditaProduto > #txtPreco"));

        $("#EnviarEditarProduto").on("click", function () {
            var model =
                {
                    "ProdutoId": $("#EditaProduto > #hdnProdutoId").val(),
                    "Descricao": $("#EditaProduto > #txtProduto").val(),
                    "Preco": $("#EditaProduto > #txtPreco").val()
                };

            MontaAjax('@Url.Action("AtualizaDadosProduto", "Comanda")', model, function (data) {
                GridProdutosLoad();
            });

        });
    });
</script>

Comanda.Site/Views/PartialViews/GridClientes.cshtml
<div class="container">
    <table class="table table-hover" id="GridClientes">
        <thead class="thead-inverse">
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Comentário</th>
                <th>Editar</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<script type="text/javascript">
    function GridClientesLoad() {        
        MontaAjax('@Url.Action("CarregaClientes", "Comanda")', "{}", function (data) {
            $("table#GridClientes > tbody").empty();
            for (var x in data) {
                $("table#GridClientes > tbody").append(
                    '<tr>' +
                      '<th scope="row">' + data[x].ClienteId + '</th>' +
                      '<td>' + data[x].Nome + '</td>' +
                      '<td>' + data[x].Comentario + '</td>' +
                      '<td><a href="#GridClientes" class="editar" title="' + data[x].Editar + '"><img style="width:30px;height:30px;" src="@Url.Content("~/Content/images/editar.png")" /></a>' +
                    '</tr>'
                );
            }

            $(".editar").on("click", function () {
                var param = { "Id": $(this).attr("title") };
                RetornaPartialView('@Url.Action("EditarCliente", "Comanda")', param, function (data) {
                    $("#ConteinerEditarCliente").html(data);
                    $("#ModalEditarCliente").modal("show");
                });
            });
        });
    }

    $("table#GridClientes").ready(function () {
        GridClientesLoad();
    });
</script>

Comanda.Site/Views/PartialViews/GridPedidos.cshtml
<table class="table table-hover" id="GridPedidos">
    <thead class="thead-inverse">
        <tr>
            <th>DataHora</th>
            <th>Cliente</th>
            <th>Comentário</th>
            <th>Produto</th>
            <th>Preço</th>
            <th>Qtd</th>
            <th>Situação</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody></tbody>
    <tfoot class="tfoot-inverse"></tfoot>
</table>
<style type="text/css">
    table > tfoot.tfoot-inverse  
    {
        background-color:#373a3c;
        color:white;
        font-weight:bolder;
    }
    table > tfoot.tfoot-inverse > tr > td > label.Seleciona
    {
        float:left;
    }
    table > tfoot.tfoot-inverse > tr > td > label.Pago
    {
        float:left;
        margin-left:20px;
    }
    table > tfoot.tfoot-inverse > tr > td > label.Pago > input
    {
        margin-right:10px;
    }
    table > tfoot.tfoot-inverse > tr > td > label.Total
    {
        float:right;
    }
</style>
<script type="text/javascript">   
    var gridpedidosparam = {
        "ClienteId": 0,
        "ProdutoId": 0,
        "DataInicio": "01/01/2000",
        "DataFim": "01/01/2000",
        "Situacao": 3
    };
    function GridPedidosLoad(gridpedidosparam) {
        MontaAjax('@Url.Action("FiltroListaPedidos", "Comanda")', gridpedidosparam, function (data) {
            $("table#GridPedidos > tbody").empty();
            $("table#GridPedidos > tfoot").empty();
            $("table#GridPedidos > tbody").append(AlimentaGrid(data));

            $(".deletar").on("click", function () {
                var param = { "datahora": $(this).attr("title") };
                MontaAjax('@Url.Action("DeletaPedido", "Comanda")', param, function (data) {
                    GridPedidosLoad(gridpedidosparam);
                });
            });
                        
            var total = 0;
            $("#GridPedidos > tbody > tr").each(function () {
                var preco = parseFloat($(this).children().eq(4).text());
                var qtd = parseInt($(this).children().eq(5).text());
                var situacao = $(this).children().eq(6).text() == "Pago" ? 1 : 0;

                total += situacao == 1 ? 0 : (preco * qtd) * (-1);
            });

            var textfoot = "<tr><td colspan='9'>" +
                           "<label class='Seleciona'>Seleciona tudo<input type='checkbox' style='margin-left:5px;' class='form-check-input tudo'></label>" +
                           "<label class='Pago'><input class='form-check-input' type='radio' name='rdSituacaoTotal' id='rdSituacaoPagoTotal' value='1'>Pago</label>" +
                           "<label class='Pago'><input class='form-check-input' type='radio' name='rdSituacaoTotal' id='rdSituacaoNaoTotal' value='2'>Não Pago</label>" +
                           "<label class='Total'><span>Total: </span>" + MascaraDinheiro(total) + "</label>" +
                           "</td></tr>"

            if ($("table#GridPedidos").parent().attr("id") == "ConteinerGridListaPedidos") {

                $("table#GridPedidos > tbody > tr").append("<td><input type='checkbox' class='form-check-input'></td>");
                $("table#GridPedidos > tfoot").append(textfoot);
                $("input[type='checkbox'].tudo").on("click", function () {
                    $("#GridPedidos > tbody > tr > td:nth-child(9) > input").prop("checked", $(this).prop("checked"));
                });

                $("label.Pago > input[name='rdSituacaoTotal']").on("click", function () {                    
                    var valor = $(this).val();                    
                    $("#GridPedidos > tbody > tr > td:nth-child(9) > input[type='checkbox']:checked").each(function () {                        
                        var thisindex = $("#GridPedidos > tbody > tr > td:nth-child(9) > input[type='checkbox']").index($(this));
                        var datahora = StringToDateTime($($(this).parent().parent().children()[0]).text());
                        var param =
                        {
                            "DataHora": datahora,
                            "Situacao": valor
                        }
                        
                        MontaAjax('@Url.Action("AtualizaSituacaoPedido", "Comanda")', param, function (data) {
                            GridPedidosLoad(gridpedidosparam);                                                       
                        });                        
                    });
                   
                });                
            }
        });
    }
    function AlimentaGrid(data) {
        var retorno = "";
        var islistapedidos = $("table#GridPedidos").parent().attr("id") == "ConteinerGridPedidos";

        for (var x in data)
        {
            if ((x < 10 && islistapedidos) || (!islistapedidos)) {
                retorno += LinhaGridTemplate(data[x].DataHora, data[x].Cliente, data[x].Comentario, data[x].Produto, data[x].Preco, data[x].Qtd, data[x].Situacao, data[x].Excluir);
            }
        }
        return retorno;
    }
    function LinhaGridTemplate(DataHora, Cliente, Comentario, Produto, Preco, Qtd, Situacao, Excluir) {

     var retorno =  '<tr>' +
                      '<th scope="row">' + DataHora + '</th>' +
                      '<td>' + Cliente + '</td>' +
                      '<td>' + Comentario + '</td>' +
                      '<td>' + Produto + '</td>' +
                      '<td>' + Preco + '</td>' +
                      '<td>' + Qtd + '</td>' +
                      '<td>' + Situacao + '</td>' +
                      '<td><a href="#GridPedidos" class="deletar" title="' + Excluir + '"><img style="width:30px;height:30px;" src="@Url.Content("~/Content/images/lixeira.jpg")" /></a></td>' +
                       '</tr>'
        return retorno;
    }
</script>

Comanda.Site/Views/PartialViews/GridProdutos.cshtml
<div class="container">
    <table class="table table-hover" id="GridProdutos">
        <thead class="thead-inverse">
            <tr>
                <th>Id</th>
                <th>Descrição</th>
                <th>Preço</th>
                <th>Editar</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<script type="text/javascript">
    function GridProdutosLoad() {
        MontaAjax('@Url.Action("CarregaProdutos", "Comanda")', "{}", function (data) {
            $("table#GridProdutos > tbody").empty();
            for (var x in data) {
                $("table#GridProdutos > tbody").append(
                    '<tr>' +
                      '<th scope="row">' + data[x].ProdutoId + '</th>' +
                      '<td>' + data[x].Descricao + '</td>' +
                      '<td>' + data[x].Preco + '</td>' +
                      '<td><a href="#GridClientes" class="editar" title="' + data[x].Editar + '"><img style="width:30px;height:30px;" src="@Url.Content("~/Content/images/editar.png")" /></a>' +
                    '</tr>'
                );
            }

            $(".editar").on("click", function () {
                var param = { "Id": $(this).attr("title") };
                RetornaPartialView('@Url.Action("EditarProduto", "Comanda")', param, function (data) {
                    $("#ConteinerEditarProduto").html(data);
                    $("#ModalEditarProduto").modal("show");
                });
            });
        });
    }

    $("table#GridProdutos").ready(function () {
        GridProdutosLoad();
    });
</script>

Comanda.Site/Views/PartialViews/Loading.cshtml
<div id="loading" class="loading">
    <img id="imgLoading" src=@Url.Content("~/Content/images/loading.gif") />    
    <span id="carregando">Carregando</span>
</div>

Comanda.Site/Views/PartialViews/Sucesso.cshtml
<style type="text/css">
    #ImgSuccess
    {        
        width:100px;
        height:100px;
    }
    #texto
    {
        text-align:center;
        text-transform:uppercase;
        color:#4CAF50;
    }
    #dvimg
    {
        margin-left: 40%;  
    }
    #dvtext
    {
       
    }
</style>

<!-- Modal -->
<div class="modal fade" id="ModalSucesso" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div id="dvimg">                                        
                   <img id="ImgSuccess" src= @Url.Content("~/Content/images/success.png") />                    
                </div>
                <div id="dvtext">
                    <p id="texto">Pedido criado com sucesso.</p>
                </div>
                </div>
            <div class="modal-footer">
                <button id="SucessoOk" type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
    $("#SucessoOk").on("click", function () {               
        LimpaFormulario();
        $("#collapseProduto").collapse("hide");
        GridPedidosLoad(gridpedidosparam);
    });    
</script>